services:
  vosk:
    image: alphacep/kaldi-ru:latest
    restart: unless-stopped
    ports:
      - "2700:2700"

  arc:
    image: ghcr.io/slavonnet/asterisk-response-classifier:latest
    restart: unless-stopped
    depends_on:
      - vosk
    ports:
      - "9099:9099"
    volumes:
      - ./config/phrases.yaml:/app/config/phrases.yaml:ro
    command:
      - /app/arc
      - -port=9099
      - -config=/app/config/phrases.yaml
      - -vosk-url=ws://vosk:2700
